### ISSUE TITLE
提供meta客户端使用的配置文件

### ISSUE THREAD

**Issue by HSK077** [QIN2DIM/tuic-installer#10]
clash-meta.yaml
感谢！

**Comment by QIN2DIM** [comment]
能否提供一个 meta type=tuic proxy 配置的最佳实践，尤其是关于 `reduce-rtt`，`congestion_control`，`udp_relay_mode` 以及其他可选项的写法。

指向同一个 server 端，我分别在 NekoRay 和 clash-verge (Windows) 启 tuic proxy，前者工作良好，但后者直接扑街了，效果非常差。（同样的客户端配置）

**Comment by QIN2DIM** [comment]
我看了一下 `clash-meta` 的源码和 `clash-verge` 的抽象实现，感觉问题出在 `clash-meta` 核心上。

在配置文件遵守最佳实践的前提下，可以认为 GUI 引导对代理性能的损耗忽略不计。

使用 `NekoRay` 和 `clash-verge` 引导 `tuic-client` 的原理不同，前者是直接调用系统命令启动预编译的 tuic-client，而 `clash-meta` 则是把原本用 Rust 实现的 `tuic-client` 用 Golang 重写了一遍，以达到通过配置文件模式匹配的方式覆盖多种代理协议的目的。

孰优孰略很难评，但从我个人的体验上说，选择直接引导预编译的可执行文件要更好一些。简单来说，Golang 和 Rust 在网络栈调用的细节上有非常微妙的差异， 反应到用户端最直接的感受就是 meta(tuic) 加载网页的速度非常慢，两者用时差距可能在2~3倍。

**Comment by HSK077** [comment]
刚看到回复上线，提供一个 meta proxy 配置 type=tuic 的最佳实践
++++++++++++++++++++++++
mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: debug
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 114.114.114.114

proxies:
  - name: Misaka-tuic
    server: xxxx
    port: 36587
    type: tuic
    uuid: xxxx-xxxx-xxxx-xxxx-xxx
    password: xxxxxxx
    ip: 0.0.0.0
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    request-timeout: 8000
    udp-relay-mode: quic
    congestion-controller: bbr

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Misaka-tuic
      
rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy

**Comment by QIN2DIM** [comment]
我已经推了一个版本，你试试行不行，反正我是感觉 meta(tuic) 和 预编译的客户端性能差距挺大的。

**Comment by QIN2DIM** [comment]
我重新看了下 meta 的文档和源码实现，发现这个项目的 DNS 路由设计极其精妙- -我觉得只这样使用 nameserver 有点太浪费了，很难称得上最佳实践=。=我再研究研究
